### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by bdowling** [sabareeshkkanan/robinhood#9]
@sabareeshkkanan -- this is some amazing work that you've pulled together.  I have been planning to do this as well, but you beat me to it, so owe you some thanks!

I have been working to make some improvements to this and plan on using it in a python implementation.

As my implementation case has some differences, trying to think how to separate those concerns from the general API schema improvements so that I can share these back with you.  

You'll see that in my branch I renamed operationIDs for example to better work in python, as well as the Multiple<<obj>> since the angle brackets aren't valid class names. 

Some of the other things I've added though include adding the tags methods, using ENUM types where appropriate, historical quotes methods, etc.

fwiw, I pushed my changes up here.. https://github.com/bdowling/robinhood-1/tree/local

Let me know your thoughts on how you'd like to see the PRs, etc, and again, Thank you for your efforts on this!

**Comment by sabareeshkkanan** [comment]
@bdowling i created a PR to see the changes. As the json and yaml are generated i will take a look at how to change at actual code

**Comment by sabareeshkkanan** [comment]
please see my comment in pr
